import jsPDF from 'jspdf';
import { format, parseISO } from 'date-fns';

interface ReceiptData {
  amount: number;
  billingDate: string;
  billType: string;
  language: 'en' | 'am';
  paidAt: string;
  tenantName: string;
}

export function downloadBillReceipt({ amount, billingDate, billType, language, paidAt, tenantName }: ReceiptData) {
  const doc = new jsPDF();
  const isAmharic = language === 'am';
  const labels = {
    title: isAmharic ? 'Payment Receipt' : 'Payment Receipt',
    tenant: isAmharic ? 'Tenant' : 'Tenant',
    type: isAmharic ? 'Bill Type' : 'Bill Type',
    billingDate: isAmharic ? 'Billing Date' : 'Billing Date',
    amount: isAmharic ? 'Amount' : 'Amount',
    paidAt: isAmharic ? 'Paid At' : 'Paid At',
    currency: 'ETB',
  };

  doc.setFontSize(20);
  doc.text('AS Apt', 20, 20);
  doc.setFontSize(16);
  doc.text(labels.title, 20, 32);

  doc.setFontSize(12);
  const rows = [
    `${labels.tenant}: ${tenantName}`,
    `${labels.type}: ${billType}`,
    `${labels.billingDate}: ${format(parseISO(billingDate), 'PPP')}`,
    `${labels.amount}: ${amount.toFixed(2)} ${labels.currency}`,
    `${labels.paidAt}: ${format(parseISO(paidAt), 'PPP p')}`,
  ];

  rows.forEach((row, index) => {
    doc.text(row, 20, 52 + index * 12);
  });

  doc.setDrawColor(180);
  doc.line(20, 118, 190, 118);
  doc.setFontSize(10);
  doc.text('Generated by AS Apt', 20, 128);

  const safeName = tenantName.toLowerCase().replace(/[^a-z0-9]+/gi, '-');
  doc.save(`${safeName}-${billType.toLowerCase()}-receipt.pdf`);
}
