import { createContext, useContext, useEffect, useMemo, useState, ReactNode } from 'react';

type Language = 'en' | 'am';

type Dictionary = Record<string, string>;

const translations: Record<Language, Dictionary> = {
  en: {
    dashboard: 'Dashboard',
    billing: 'Billing',
    tenants: 'Tenants',
    settings: 'Settings',
    signOut: 'Sign Out',
    admin: 'Admin',
    poweredBy: 'Powered by',
    language: 'Language',
    activeTenants: 'Active Tenants',
    unpaidElectric: 'Unpaid Electric',
    unpaidWater: 'Unpaid Water',
    overdue: 'Overdue',
    tenantPaymentStatus: 'Tenant Payment Status',
    noActiveTenants: 'No active tenants yet.',
    unassigned: 'Unassigned',
    daysOverdue: 'd overdue',
    daysLeft: 'd left',
    add: 'Add',
    addTenant: 'Add Tenant',
    editTenant: 'Edit Tenant',
    name: 'Name',
    phone: 'Phone',
    apartment: 'Apartment',
    selectApartment: 'Select apartment',
    moveInDate: 'Move-in Date',
    rentPrice: 'Rent Price',
    paymentPeriod: 'Payment Period',
    save: 'Save',
    noTenantsYet: 'No tenants yet. Add your first tenant.',
    removeTenantConfirm: 'Remove this tenant?',
    tenantUpdated: 'Tenant updated',
    tenantAdded: 'Tenant added',
    tenantRemoved: 'Tenant removed',
    fillRequiredFields: 'Please fill required fields',
    electricity: 'Electricity',
    water: 'Water',
    addBill: 'Add Bill',
    addElectricityBill: 'Add Electricity Bill',
    addWaterBill: 'Add Water Bill',
    selectTenant: 'Select tenant',
    billingDate: 'Billing Date',
    kwhUsed: 'kWh Used',
    rate: 'Rate (ETB/kWh)',
    amount: 'Amount (ETB)',
    formula: 'Formula',
    total: 'Total',
    noElectricityBills: 'No electricity bills yet.',
    noWaterBills: 'No water bills yet.',
    paid: 'Paid',
    pay: 'Pay',
    downloadPdf: 'PDF',
    electricityBillAdded: 'Electricity bill added',
    waterBillAdded: 'Water bill added',
    markedAsPaid: 'Marked as paid',
    fillAllFields: 'Fill all fields',
    paymentReceipt: 'Payment Receipt',
    billType: 'Bill Type',
    tenant: 'Tenant',
    paidAt: 'Paid At',
    receiptDownloaded: 'Receipt downloaded',
    changePassword: 'Change Password',
    update: 'Update',
    exportReports: 'Export Reports',
    exportPdf: 'Export PDF',
    exportCsv: 'Export CSV/Excel',
    userManagement: 'User Management',
    noUsersFound: 'No users found.',
    approved: 'Approved',
    pending: 'Pending',
    approve: 'Approve',
    passwordUpdated: 'Password updated',
    passwordMin: 'Password must be at least 6 characters',
    userApproved: 'User approved',
    csvExported: 'CSV exported',
    pdfExportOpened: 'PDF export opened',
    pleaseAllowPopups: 'Please allow popups',
    loginTitle: 'AS Apt',
    loginSubtitle: 'Alehegne Sewnet Apartment',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    noAccount: "Don't have an account?",
    register: 'Register',
    registerTitle: 'Register',
    registerSubtitle: 'Request access to AS Apt',
    fullName: 'Full Name',
    registering: 'Registering...',
    alreadyHaveAccount: 'Already have an account?',
    registrationSuccess: 'Registration successful! Please wait for admin approval.',
    awaitingApproval: 'Awaiting Approval',
    awaitingApprovalMessage: 'Your account is pending admin approval. Please check back later.',
    checkingAuthentication: 'Checking authentication...',
    loadingApp: 'Loading app...',
    loadingPage: 'Loading page...',
    pageNotFound: 'Oops! Page not found',
    returnHome: 'Return to Home',
  },
  am: {
    dashboard: 'ዳሽቦርድ',
    billing: 'ቢሊንግ',
    tenants: 'ተከራዮች',
    settings: 'ቅንብሮች',
    signOut: 'ውጣ',
    admin: 'አድሚን',
    poweredBy: 'የተሰራው በ',
    language: 'ቋንቋ',
    activeTenants: 'ንቁ ተከራዮች',
    unpaidElectric: 'ያልተከፈለ መብራት',
    unpaidWater: 'ያልተከፈለ ውሃ',
    overdue: 'ዘግይቷል',
    tenantPaymentStatus: 'የተከራዮች ክፍያ ሁኔታ',
    noActiveTenants: 'እስካሁን ንቁ ተከራዮች የሉም።',
    unassigned: 'አልተመደበም',
    daysOverdue: 'ቀን ዘግይቷል',
    daysLeft: 'ቀን ቀርቷል',
    add: 'ጨምር',
    addTenant: 'ተከራይ ጨምር',
    editTenant: 'ተከራይ አርትዕ',
    name: 'ስም',
    phone: 'ስልክ',
    apartment: 'አፓርታማ',
    selectApartment: 'አፓርታማ ይምረጡ',
    moveInDate: 'የገባበት ቀን',
    rentPrice: 'የኪራይ ዋጋ',
    paymentPeriod: 'የክፍያ ጊዜ',
    save: 'አስቀምጥ',
    noTenantsYet: 'እስካሁን ተከራዮች የሉም። የመጀመሪያውን ተከራይ ያክሉ።',
    removeTenantConfirm: 'ይህን ተከራይ ማስወገድ ይፈልጋሉ?',
    tenantUpdated: 'ተከራይ ተሻሽሏል',
    tenantAdded: 'ተከራይ ተጨምሯል',
    tenantRemoved: 'ተከራይ ተወግዷል',
    fillRequiredFields: 'እባክዎ አስፈላጊ መረጃዎችን ይሙሉ',
    electricity: 'መብራት',
    water: 'ውሃ',
    addBill: 'ቢል ጨምር',
    addElectricityBill: 'የመብራት ቢል ጨምር',
    addWaterBill: 'የውሃ ቢል ጨምር',
    selectTenant: 'ተከራይ ይምረጡ',
    billingDate: 'የቢል ቀን',
    kwhUsed: 'የተጠቀመው kWh',
    rate: 'ዋጋ (ብር/kWh)',
    amount: 'መጠን (ብር)',
    formula: 'ፎርሙላ',
    total: 'ጠቅላላ',
    noElectricityBills: 'እስካሁን የመብራት ቢሎች የሉም።',
    noWaterBills: 'እስካሁን የውሃ ቢሎች የሉም።',
    paid: 'ተከፍሏል',
    pay: 'ክፈል',
    downloadPdf: 'PDF',
    electricityBillAdded: 'የመብራት ቢል ተጨምሯል',
    waterBillAdded: 'የውሃ ቢል ተጨምሯል',
    markedAsPaid: 'እንደተከፈለ ተመዝግቧል',
    fillAllFields: 'ሁሉንም መረጃ ይሙሉ',
    paymentReceipt: 'የክፍያ ደረሰኝ',
    billType: 'የቢል አይነት',
    tenant: 'ተከራይ',
    paidAt: 'የተከፈለበት ጊዜ',
    receiptDownloaded: 'ደረሰኝ ወርዷል',
    changePassword: 'የይለፍ ቃል ቀይር',
    update: 'አዘምን',
    exportReports: 'ሪፖርቶችን አውጣ',
    exportPdf: 'PDF አውጣ',
    exportCsv: 'CSV/Excel አውጣ',
    userManagement: 'የተጠቃሚ አስተዳደር',
    noUsersFound: 'ምንም ተጠቃሚ አልተገኘም።',
    approved: 'ጸድቋል',
    pending: 'በመጠባበቅ ላይ',
    approve: 'አጽድቅ',
    passwordUpdated: 'የይለፍ ቃል ተዘምኗል',
    passwordMin: 'የይለፍ ቃል ቢያንስ 6 ፊደላት መሆን አለበት',
    userApproved: 'ተጠቃሚው ጸድቋል',
    csvExported: 'CSV ወጥቷል',
    pdfExportOpened: 'PDF ተከፍቷል',
    pleaseAllowPopups: 'እባክዎ ፖፕአፕ ይፍቀዱ',
    loginTitle: 'AS Apt',
    loginSubtitle: 'አለኸኝ ሰውነት አፓርታማ',
    email: 'ኢሜይል',
    password: 'የይለፍ ቃል',
    signIn: 'ግባ',
    signingIn: 'በመግባት ላይ...',
    noAccount: 'አካውንት የለዎትም?',
    register: 'ይመዝገቡ',
    registerTitle: 'ይመዝገቡ',
    registerSubtitle: 'ወደ AS Apt መዳረሻ ይጠይቁ',
    fullName: 'ሙሉ ስም',
    registering: 'በመመዝገብ ላይ...',
    alreadyHaveAccount: 'አካውንት አለዎት?',
    registrationSuccess: 'ምዝገባው ተሳክቷል! እባክዎ የአድሚን ፍቃድ ይጠብቁ።',
    awaitingApproval: 'ፍቃድ በመጠባበቅ ላይ',
    awaitingApprovalMessage: 'አካውንትዎ የአድሚን ፍቃድ በመጠባበቅ ላይ ነው። በኋላ ይመልሱ።',
    checkingAuthentication: 'ማረጋገጫ በመፈተሽ ላይ...',
    loadingApp: 'መተግበሪያው በመጫን ላይ...',
    loadingPage: 'ገጹ በመጫን ላይ...',
    pageNotFound: 'ይቅርታ! ገጹ አልተገኘም',
    returnHome: 'ወደ መነሻ ተመለስ',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en';
    const stored = window.localStorage.getItem('app-language');
    return stored === 'am' ? 'am' : 'en';
  });

  useEffect(() => {
    window.localStorage.setItem('app-language', language);
    document.documentElement.lang = language === 'am' ? 'am' : 'en';
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage: setLanguageState,
      t: (key: string) => translations[language][key] ?? translations.en[key] ?? key,
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
